### PR TITLE
Version 1.1.0

### PR DESCRIPTION
**Pull request by nitriques**
This is a chance for you to test it!

Will be release very soon.

Thanks.

### CODE REVIEW

**Comment by twiro** [comment]
Wow - Thank you, Nicolas. Great and very appreciated work on this extension!

i just gave it a quick test (freshyl installed the extension in a test setup) and got the following error when trying to add a systemdate-field to a section:

    Symphony Fatal Database Error: Unknown column 'show_time' in 'field list'

Looks like the new settings aren't included in the database setup. Will post a PR!

**Comment by twiro** [comment]
Done: https://github.com/symphonists/system_date_fields/pull/15

@nitriques - just to be sure (and learn)... is this the right way to contribute? Creating a Branch for the fix and send a PR against integration branch? Or should anything be done different?

**Comment by twiro** [comment]
Found another bug and opened a new issue https://github.com/symphonists/system_date_fields/issues/16 as I think this is a little over my head...

**Comment by nitriques** [comment]
> Looks like the new settings aren't included in the database setup. Will post a PR!

Damn. My bad! Thanks for the PR!

>  just to be sure (and learn)... is this the right way to contribute?

It's perfect!

**Comment by nitriques** [comment]
@twiro Bug should be fixed now. Would you mind testing please ? I think everything is ok now.

I've also refactored the code because I was tired of fixing bugs twice :)

**Comment by twiro** [comment]
> _Bug should be fixed now. Would you mind testing please ? I think everything is ok now._

Tested and works like a charm now :) Thank you very much!

One thing though - other extensions (Members, Member last visit) also include fields that serve the simple purpose of showing a "label" and a "date" in the publish entry area. But they use a different styling approach:

screen shot 2015-12-14 at 20 17 38

I don't think one of both style-approaches is perfect regarding a clean and polished publish area, but I think staying consistent with the already introduced style would be the the better choice for now.

What do you think? Should I take care of this?

**Comment by nitriques** [comment]
> I don't think one of both style-approaches is perfect regarding a clean and polished publish area, but I think staying consistent with the already introduced style would be the the better choice for now.

You're right! I always wanted to display it nicer, but never had any idea. I am a software engineer, not a designer, sadly.

> What do you think? Should I take care of this?

Please never hesitate to send a PRs! It's always a good starting point for discussion. Please submit it against integration branch :) If you can't do it now, I do not mind releasing 1.2.0 with it :) Thanks!

**Comment by twiro** [comment]
> _ You're right! I always wanted to display it nicer, but never had any idea. I am a software engineer, not a designer, sadly._

And I'm a designer, not a software engineer - sadly too though ;) Wish I could code better...

But maybe Design/UI is an area where I could contribute a little more to Symphony. Trying to figure out a better solution for displaying these fields might be a good start! 

If you could wait till tomorrow I could send a PR that aligns the styling to the other mentioned fields in the morning. That might be a pragmatic solution for 1.1 if you're ok with that.

After that I can take my time and try to find a better allover solution for this kind fo fields...

**Comment by nitriques** [comment]
Super! We make a nice duo then :)

**Comment by twiro** [comment]
> _If you could wait till tomorrow I could send a PR that aligns the styling to the other mentioned fields in the morning. That might be a pragmatic solution for 1.1 if you're ok with that._

After having had another look I decided to look for a better solution right away - posted my proposal at the issue tracker of the core: https://github.com/symphonycms/symphony-2/issues/2532

Let me know what you think and I'll try to implement what's needed.

> _Super! We make a nice duo then :)_

Let's hope for the best :) I am still a git- and open-source-noob, but I'd really like to contribute a little more than I did in the past - so feel free to contact me if you need help regarding things interface/design-related. And I will surely turn to you with some technical advice from time to time - have some ideas floating around regarding symphony that I probably won't be able to implement solely by myself.

**Comment by nitriques** [comment]
> I am still a git- and open-source-noob,

I'm here to help :)

> so feel free to contact me if you need help regarding things interface/design-related

Great!

**Comment by twiro** [comment]
> _I'm here to help :)_

Great - and thanks for this update Nicolas!

I will take care of the styling issue right after [this](https://github.com/symphonycms/symphony-2/issues/2532) has been implemented (Symphony 2.6.5 hopefully)!

Should I prep up a new version then?
That would be "**1.1.1**" then, right?

**Comment by nitriques** [comment]
> and thanks for this update Nicolas!

You're welcome!

> That would be "1.1.1" then, right?

Yes, or even 1.2.0. I prefer to release often instead of letting the code base sleep. Please send PR when ready !

**Pull request merged**
