### PR TITLE
Style field value readonly

### PR DESCRIPTION
**Pull request by twiro**
This PR adds the class `field-value-readonly` to the fields readonly values in the publish entry area.

This class has been introduced in Symphony 2.6.5 to unify the styling of readonly values among different extensions.

To avoid raising the minimum requirements for this extension just because of a styling update I additionally added fallback-styles in the css. These will be redundant once this extension stops supporting Symphony 2.6.4 (and therefore can be deleted as soon as this will be the case).

### CODE REVIEW

**Comment by twiro** [comment]
@nitriques - does this look ok for you?
If so I will try to apply the styling to the other affected extensions as well (members, members last visit).

**Comment by nitriques** [comment]
Yup it does. I do not know why my merge commit is in there tho...

**Comment by nitriques** [comment]
But it should be 1.2 since it's a new feature :) can you edit that please ?

**Comment by twiro** [comment]
> _Yup it does._

Great!

> _I do not know why my merge commit is in there tho..._

Me neither... I'm just getting started with the "GitHub Desktop" app and somehow this commit showed up after syncing - is this a problem in regard to pulling this PR in? If so, anything I can do to get rid of that commit in my PR? Will try my best to avoid things like this in the future!

> _But it should be 1.2 since it's a new feature :) can you edit that please ?_

Fixed!

**Comment by nitriques** [comment]
> I'm just getting started with the "GitHub Desktop" app

That would explain it ;)

> is this a problem in regard to pulling this PR in? 

Nope!

>  If so, anything I can do to get rid of that commit in my PR? 

You could, but I am happy to deal with it.

> Will try my best to avoid things like this in the future!

No worries!

**Comment by nitriques** [comment]
> Fixed!

We now use semver and it requires 3 digits ;)  But that's my fault I guess ;) [It's fixed and released](https://github.com/symphonists/system_date_fields/releases/tag/1.2.0) ! Thanks again!

**Pull request closed without merging**
